getEntityIdentifierValue() can now return null
thesalegroup/restorm pull request #48
Opened 2018-06-18 15:36 UTC by PrincessSparkle

Fixes #

## Proposed Changes

  -
  -
  -

2018-06-18 15:38 UTC, robwasripped requested changes
Can you add some comments to the changes please? The need for this will get forgotten.

2018-06-19 07:12 UTC, karolbatkowskitsg submitted a review, later dismissed

2018-06-19 07:57 UTC, karolbatkowskitsg submitted a review, later dismissed

2018-06-19 08:33 UTC, robwasripped approved these changes

2018-06-19 08:33 UTC, merged